apiVersion: apps/v1beta1 
kind: Deployment
metadata: 
  name: nginx-app-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: dotnetcore
        image: workshopdeployacr.azurecr.io/nginx
        ports:
        - name: nginx-app
          containerPort: 80